apiVersion: v1
kind: Service
metadata:
  labels: {{ include "restapi-flask-demo.labels" . | nindent 4 }}
  name: {{ include "restapi-flask-demo.fullname" . }}
spec:
  ports:
  - port: {{ .Values.appPort | default 5000 }}
  selector:
    app: {{ include "restapi-flask-demo.fullname" . }}
